# Generated by Django 3.2.15 on 2022-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
