# Generated by Django 3.2.15 on 2022-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_attachment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
